import { MetadataRoute } from 'next';
import { supabase } from '@/lib/supabase';
import { allStateSlugs } from '@/lib/state-pricing';

const stateAbbreviations = [
    'al', 'ak', 'az', 'ar', 'ca', 'co', 'ct', 'de', 'fl', 'ga',
    'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky', 'la', 'me', 'md',
    'ma', 'mi', 'mn', 'ms', 'mo', 'mt', 'ne', 'nv', 'nh', 'nj',
    'nm', 'ny', 'nc', 'nd', 'oh', 'ok', 'or', 'pa', 'ri', 'sc',
    'sd', 'tn', 'tx', 'ut', 'vt', 'va', 'wa', 'wv', 'wi', 'wy'
  ];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
    const baseUrl = 'https://funeralhomedirectories.com';

  // Static pages
  const staticPages = [
    { url: baseUrl, lastModified: new Date(), changeFrequency: 'weekly' as const, priority: 1.0 },
    { url: `${baseUrl}/states`, lastModified: new Date(), changeFrequency: 'weekly' as const, priority: 0.9 },
    { url: `${baseUrl}/about`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.5 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.5 },
    { url: `${baseUrl}/blog`, lastModified: new Date(), changeFrequency: 'weekly' as const, priority: 0.8 },
    { url: `${baseUrl}/funeral-costs`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.7 },
    { url: `${baseUrl}/veteran-burial-benefits`, lastModified: new Date(), changeFrequency: 'monthly' as const, priority: 0.7 },
      ];

  const funeralCostStatePages = allStateSlugs.map((slug) => ({
    url: `${baseUrl}/funeral-costs/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  // Blog posts
  const blogPosts = [
    'cremation-costs-2026',
    'cremation-near-me',
    'cremation-cost-san-jose',
    'direct-cremation-vs-traditional-funeral',
    'funeral-homes-los-angeles',
    'best-funeral-homes-nashville-tn',
    'funeral-homes-atlanta-ga',
    'funeral-homes-houston-tx',
    'funeral-homes-memphis-tn',
    'funeral-homes-chicago-il',
    'how-to-write-an-obituary',
    'how-long-can-a-funeral-home-hold-a-body',
    'what-is-a-celebration-of-life',
    'best-prepaid-funeral-plans',
    'what-to-do-after-a-funeral',
    'end-of-life-planning-checklist',
    'what-happens-if-you-cant-afford-a-funeral',
    'questions-to-ask-a-funeral-director',
    'eulogy-for-friend-samples',
    'what-to-do-with-ashes-after-cremation',
    'bible-verses-for-funerals',
    'what-happens-to-the-body-during-cremation',
    'how-to-choose-a-funeral-home',
    'what-is-a-graveside-service',
    'memorial-service-bulletins',
    'jewish-funeral-etiquette',
    'what-is-a-funeral-celebrant',
    'obituary-examples',
    'christian-funeral-songs',
    'thank-you-notes-after-funeral',
    'green-burial-options',
    'pallbearer-guide',
    'words-of-comfort-for-grieving-family',
    'pet-loss-grief',
    'what-happens-to-hsa-when-you-die',
    'average-burial-cost',
    'free-funeral-planning-guide',
    'what-to-wear-to-a-funeral',
    'how-long-does-a-funeral-last',
    'funeral-flowers-guide',
    'grief-stages-explained',
    'how-to-support-a-grieving-friend',
    'military-funeral-honors',
    'catholic-funeral-traditions',
    'muslim-funeral-traditions',
    'death-certificate-guide',
    'cremation-jewelry',
    'scattering-ashes-guide',
    'funeral-etiquette-guide',
    'obituary-vs-death-notice',
    'how-to-write-a-eulogy',
    'funeral-pre-planning-checklist',
    'what-is-a-viewing-vs-visitation',
    'how-long-after-death-is-a-funeral',
    'home-funerals-guide',
    'body-donation-to-science',
    'average-cemetery-plot-cost',
    'funeral-insurance-guide',
    'social-security-death-benefit',
    'what-happens-to-debt-when-you-die',
    'embalming-explained',
    'how-to-read-a-funeral-home-general-price-list',
    'ftc-funeral-rule-explained',
    'urns-guide',
    'aquamation-guide',
    'natural-organic-reduction',
    'columbarium-guide',
    'how-to-write-a-condolence-card',
    'funeral-readings-and-poems',
    'what-to-say-at-a-funeral',
    'mausoleum-burial-guide',
    'non-religious-funeral-options',
    'grief-counseling-guide',
    'children-and-grief',
    'loss-of-spouse-guide',
    'loss-of-parent-guide',
    'grief-after-sudden-death',
    'hindu-funeral-traditions',
    'buddhist-funeral-traditions',
    'veteran-headstones-and-markers',
    'national-cemetery-guide',
    'how-to-close-deceased-accounts',
    'digital-estate-planning',
    'living-will-vs-advance-directive',
    'medicaid-funeral-assistance',
    'notifying-agencies-after-death',
    'food-for-funeral-reception',
    'sample-eulogy-for-mother-from-daughter',
    'donations-at-a-funeral',
    'funeral-homes-that-offer-payment-plans',
    'scripture-readings-for-funerals',
    'poems-for-loss-of-father',
    'prayer-of-the-faithful-funeral',
    'funeral-hymns',
    'what-is-a-funeral-service',
    'amazing-grace-hymn',
    'classical-music-for-funerals',
    'condolence-text-message',
    'funeral-home-payment-plans',
    'condolence-text-messages',
    'hidden-funeral-costs-tennessee',
    'what-affects-funeral-costs-tennessee',
    'cremation-vs-burial-cost-tennessee',
    'low-cost-funeral-options-nashville',
    'funeral-financial-assistance-tennessee',
    'wichita-obituaries',
    'milwaukee-obituaries',
    'huntsville-obituaries',
    'missoula-obituaries',
    'greensboro-obituaries',
    'tucson-obituaries',
    'san-diego-obituaries',
    'spokane-obituaries',
    'phoenix-obituaries',
    'chicago-obituaries',
    'baltimore-obituaries',
    'atlanta-obituaries',
    'denver-obituaries',
    'lincoln-ne-obituaries',
    'san-francisco-obituaries',
    'boise-obituaries',
    'orlando-obituaries',
    'virginia-beach-obituaries',
    'norfolk-obituaries',
    'raleigh-obituaries',
    'tacoma-obituaries',
    'oklahoma-city-obituaries',
    'tulsa-obituaries',
    'peoria-il-obituaries',
    'bowling-green-ky-obituaries',
    'anchorage-obituaries',
    'winston-salem-obituaries',
    'columbus-ohio-obituaries',
    'st-louis-obituaries',
    'indianapolis-obituaries',
    'detroit-obituaries',
    'tampa-obituaries',
    'fresno-obituaries',
    'miami-obituaries',
    'funeral-flowers-delivery',
    'sympathy-card-messages',
    'condolence-messages',
    'anticipatory-grief',
    'disenfranchised-grief',
    'grief-support-groups',
    'celebration-of-life-ideas',
    'sympathy-gift-ideas',
    'eulogy-for-mother',
    'eulogy-for-father',
    'eulogy-for-grandmother',
    'eulogy-for-brother',
    'memorial-service-ideas',
    'memorial-table-ideas',
    'memorial-garden-ideas',
    'memory-jar-ideas',
    'funeral-program-ideas',
    'how-long-does-grief-last',
    'what-to-say-when-someone-loses-a-parent',
    'grief-journal-prompts',
    'celebration-of-life-food-ideas',
    'memory-book-for-funeral',
    'headstone-cost',
    'headstone-wording-examples',
    'grief-vs-depression',
    'how-to-find-a-grave',
    'death-anniversary',
    'small-estate-affidavit',
    'probate-guide',
    'life-insurance-after-death',
    'estate-executor-duties',
    'cemetery-plot-cost',
    'complicated-grief',
    'grief-exhaustion',
    'accessing-deceased-accounts',
    'funeral-financial-assistance',
    'eulogy-for-grandfather',
    'eulogy-for-sister',
    'eulogy-for-spouse',
    'eulogy-for-aunt-or-uncle',
    'how-to-write-a-will',
    'power-of-attorney-guide',
    'hospice-guide',
    'palliative-care-vs-hospice',
    'signs-of-dying',
    'what-to-say-to-someone-who-is-dying',
    'what-is-a-dnr',
    'organ-donation-guide',
    'miscarriage-grief',
    'suicide-loss-grief',
    'caregiver-grief',
    'alternative-burial-methods',
    'traveling-with-ashes',
    'obituary-templates',
    'cheapest-cremation-near-me',
    'funeral-songs-guide',
    'death-doula-guide',
    'memorial-keepsakes',
    'explaining-death-to-children',
    'losing-a-child',
    'grief-books',
    'grief-after-divorce',
    'birthday-of-deceased-loved-one',
    'grief-therapy-guide',
    'funeral-outfit-ideas',
    'dating-after-loss',
    'announcing-death-on-social-media',
    'ambiguous-loss',
    'grief-brain-fog',
    'holidays-after-loss',
    'victorian-mourning-customs',
  ].map((slug) => ({
    url: `${baseUrl}/blog/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }));

  // State pages
  const statePages = stateAbbreviations.map((state) => ({
        url: `${baseUrl}/funeral-homes/${state}`,
        lastModified: new Date(),
        changeFrequency: 'weekly' as const,
        priority: 0.8,
  }));

  // Get all cities from database
  const { data: homes } = await supabase
      .from('funeral_homes')
      .select('city, state')
      .range(0, 10000);

  const citySet = new Set<string>();
    homes?.forEach((home) => {
          if (home.city && home.state) {
                  const citySlug = home.city.toLowerCase().replace(/\s+/g, '-');
                  const stateSlug = home.state.toLowerCase();
                  citySet.add(`${stateSlug}/${citySlug}`);
          }
    });

  const cityPages = Array.from(citySet).map((cityState) => ({
        url: `${baseUrl}/funeral-homes/${cityState}`,
        lastModified: new Date(),
        changeFrequency: 'weekly' as const,
        priority: 0.7,
  }));

  return [...staticPages, ...blogPosts, ...statePages, ...funeralCostStatePages, ...cityPages];
}
